# Generated by Django 5.2.5 on 2025-08-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
